### ISSUE TITLE
Section ID does not match. Should be 2 is 3 error

### ISSUE THREAD

**Issue by wildtang** [MeteoGroup/grib-library#4]
I use your lib to read my grib2 file, but exception below occured.
To figure out the problem I can provide my grib2 file to you if you need it.

org.meteogroup.griblibrary.exception.GribReaderException: Section ID does not match. Should be 2 is 3
    at org.meteogroup.griblibrary.grib2.Grib2RecordReader.readCompleteRecord(Grib2RecordReader.java:82)
    at org.meteogroup.griblibrary.grib2.Grib2CollectionReader.readAllRecords(Grib2CollectionReader.java:81)
    at org.meteogroup.griblibrary.grib2.Grib2CollectionReader.readFileFromFileName(Grib2CollectionReader.java:58)
    at cn.robusoft.grib.Main.main(Main.java:16)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.io.IOException: Section ID does not match. Should be 2 is 3
    at org.meteogroup.griblibrary.grib2.Grib2LUSReader.readLUSValues(Grib2LUSReader.java:23)
    at org.meteogroup.griblibrary.grib2.Grib2RecordReader.readCompleteRecord(Grib2RecordReader.java:68)
    ... 8 more

**Comment by wildtang** [comment]
I think the problem is Section 2 of GRIB2( Local Use Section ) is  optional,
and my grib2 file has not this section

**Comment by a613** [comment]
Same thing here. I am using Canadian weather files: http://dd.weather.gc.ca/model_gem_regional/10km/grib2/
